name: Build ESP32 Firmware

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: espressif/idf:release-v4.4

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Compile with ESP-IDF
      run: |
        cd ESP32/source/firmware
        # Configuramos el entorno seguro para el contenedor
        git config --global --add safe.directory /__w/${{ github.event.repository.name }}/${{ github.event.repository.name }}
        # Compilamos el proyecto
        idf.py build

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: esp32-switch-firmware
        path: |
          ESP32/source/firmware/build/*.bin
          ESP32/source/firmware/build/partition_table/*.bin
          ESP32/source/firmware/build/bootloader/*.bin
